apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pod-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pod-k8s
  template:
    metadata:
      labels:
        app: ml-pod-k8s
    spec:
      containers:
        - name: redis-container
          image: gcr.io/c23-pr513-capstone/redis-server:v0.2
          ports:
            - containerPort: 6379
              name: redis-server
            - containerPort: 8001
              name: redis-client
        - name: front-server-container
          image: gcr.io/c23-pr513-capstone/ml-server:v0.2
          ports:
            - containerPort: 8000
              name: ml-front-server
            - containerPort: 9898
              name: ml-config-env
          env:
            - name: PORT
              value: "9898"
            - name: REDIS_HOST
              value: "redis-container"
            - name: REDIS_PORT
              value: "6379"
        - name: nginx-container
          image: nginx:1.19.6
          ports:
            - containerPort: 80
              name: nginx
